      
management:
   security:
      enabled: false
   endpoints:
      web:
         exposure:
            include: '*'

#RabbitMQ connection details
spring:
   rabbitmq:
      host: localhost
      port: 15672
      username: guest
      password: guest             